apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: sba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: registry.cn-beijing.aliyuncs.com/damondocker/eurake:{version}
          ports:
            - name: http-port
              containerPort: 8761
          env:
            - name: spring_profiles_active
              value: k8s
      imagePullSecrets:
        - name: sba